// Code generated by goctl. DO NOT EDIT.
// Source: exchange_rate.proto

package server

import (
	"context"
	rate2 "grpc-common/market/rate"
	"market/internal/domain"
	"market/internal/logic"
	"market/internal/svc"
)

type ExchangeRateServer struct {
	svcCtx *svc.ServiceContext
	rate2.UnimplementedExchangeRateServer
}

func NewExchangeRateServer(svcCtx *svc.ServiceContext) *ExchangeRateServer {
	return &ExchangeRateServer{
		svcCtx: svcCtx,
	}
}

func (s *ExchangeRateServer) UsdRate(ctx context.Context, in *rate2.RateReq) (*rate2.RateRes, error) {
	l := logic.NewExchangeRateLogic(ctx, s.svcCtx, domain.NewExchangeRateDomain())
	return l.GetUsdRate(in)
}
