// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type (
	CodeReq struct {
		Phone string `json:"phone"`
	}
	CodeRes struct {
		Code string `json:"code"`
	}
)

type (
	LoginReq struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
	LoginRes struct {
		Username      string `json:"username"`
		Token         string `json:"token"`
		MemberLevel   string `json:"memberLevel"`
		RealName      string `json:"realName"`
		Country       string `json:"country"`
		Avatar        string `json:"avatar"`
		PromotionCode string `json:"promotionCode"`
		Id            int64  `json:"id"`
		LoginCount    int    `json:"loginCount"`
		SuperPartner  string `json:"superPartner"`
		MemberRate    int    `json:"memberRate"`
	}
)
