// Code generated by goctl. DO NOT EDIT.
// Source: exchange_rate.proto

package mkclient

import (
	"context"
	rate2 "grpc-common/market/rate"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RateReq = rate2.RateReq
	RateRes = rate2.RateRes

	ExchangeRate interface {
		UsdRate(ctx context.Context, in *RateReq, opts ...grpc.CallOption) (*RateRes, error)
	}

	defaultExchangeRate struct {
		cli zrpc.Client
	}
)

func NewExchangeRate(cli zrpc.Client) ExchangeRate {
	return &defaultExchangeRate{
		cli: cli,
	}
}

func (m *defaultExchangeRate) UsdRate(ctx context.Context, in *RateReq, opts ...grpc.CallOption) (*RateRes, error) {
	client := rate2.NewExchangeRateClient(m.cli.Conn())
	return client.UsdRate(ctx, in, opts...)
}
